import type { SyncDependencies } from "./shared.js";
import { syncCountries } from "./countries.js";
import { syncTypes } from "./types.js";
import { syncLeagues } from "./leagues.js";
import { syncSeasons } from "./seasons.js";
import { syncVenues } from "./venues.js";
import { syncStructure } from "./structure.js";
import { syncTeams } from "./teams.js";
import { syncPlayers } from "./players.js";
import { syncSquadMemberships } from "./squad-memberships.js";
import { syncStates } from "./states.js";
import { syncFixtures } from "./fixtures.js";
import { syncFixtureDetails } from "./fixture-details.js";
import { syncCoaches } from "./coaches.js";
import { syncReferees } from "./referees.js";
import { syncTransfers } from "./transfers.js";
import { syncSidelined } from "./sidelined.js";
import { syncStandings } from "./standings.js";

export async function syncBase(dependencies: SyncDependencies): Promise<void> {
  dependencies.log.info("🚀 Starting sync:base");
  await syncCountries(dependencies);
  await syncTypes(dependencies);
  await syncLeagues(dependencies);
  await syncSeasons(dependencies);
  await syncVenues(dependencies);
  await syncStructure(dependencies);
  await syncTeams(dependencies);
  await syncCoaches(dependencies);
  await syncReferees(dependencies);
  await syncPlayers(dependencies);
  await syncSquadMemberships(dependencies);
  await syncStates(dependencies);
  await syncFixtures(dependencies);
  await syncFixtureDetails(dependencies);
  await syncTransfers(dependencies);
  await syncSidelined(dependencies);
  await syncStandings(dependencies);
  dependencies.log.info("🎉 Sync Finished Successfully");
}
